
FROM jenkins/jenkins:20190226

USER root
#to do 安装python3 software如果是目录后面需要添加/
ADD install-python3.sh  /software/
ADD install-ansible.sh  /software/
RUN chmod +x /software/install-python3.sh && chmod +x /software/install-ansible.sh \
  && /software/install-python3.sh \
  && /software/install-ansible.sh


RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

USER jenkins
# Here you can install some Jenkins plugins if you want
